### ISSUE TITLE
a issue

### ISSUE THREAD

**Issue by Atlanti1s** [ZekerZhayard/CompatibilityLayerForCustomSkinLoader#2]
[04:18:26] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:18:26] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[04:18:26] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[04:18:26] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[04:18:26] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jdk1.8.0_251\jre
[04:18:26] [main/ERROR]: Failed to load dependencies.info from [基础]1.7.10伤害与血量显示mcmap.ccDamageIndicators  v3.2.0.jar as JSON
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.util.zip.ZipException: error in opening zip file
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.zip.ZipFile.open(Native Method)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:505)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:499)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:447)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:586)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:54)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.newInstance(Class.java:442)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:18:26] [main/WARN]: Warning: version of ForgeMultipart, 1.2.7 is newer than request 1.2.0.347
[04:18:26] [main/WARN]: Warning: version of Baubles, 1.0.1.14 is newer than request 1.0.1.10
[04:18:26] [main/WARN]: The coremod DummyCore.ASM.DCLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/ERROR]: Unable to read the jar file [基础]1.7.10伤害与血量显示mcmap.ccDamageIndicators  v3.2.0.jar - ignoring
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_251]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_251]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_251]
	at java.util.jar.JarFile.<init>(JarFile.java:167) ~[?:1.8.0_251]
	at java.util.jar.JarFile.<init>(JarFile.java:131) ~[?:1.8.0_251]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[04:18:26] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/WARN]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/INFO]: [AppEng] Core Init
[04:18:26] [main/WARN]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/WARN]: The coremod makeo.gadomancy.coremod.GadomancyCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from CompatibilityLayerForCustomSkinLoader-ALPHA-11.jar
[04:18:26] [main/INFO]: Loading tweaker customskinloader.forge.ForgeTweaker from CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323 .jar
[04:18:26] [main/INFO]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from 【优化】更好的FPSBetterFps-1.0.1.jar
[04:18:26] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from 【优化】高清修复DOptiFine_1.7.10_HD_U_E7.jar
[04:18:26] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/WARN]: The coremod lain.mods.inputfix.InputFix does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/INFO]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from 【基础】小地图前置-1.7.10.jar
[04:18:26] [main/WARN]: The coremod com.anotherera.core.AnotherCommonBugFix does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[04:18:26] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[04:18:26] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[04:18:26] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:971)
[04:18:26] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)

**Comment by ZekerZhayard** [comment]
你没装前置 https://www.curseforge.com/minecraft/mc-mods/mixinbootstraplegacy/files/3798697
